# Generated by Django 4.1.5 on 2023-01-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=30)),
                ('actor_image', models.ImageField(blank=True, default='default_actor.jpg', upload_to='')),
                ('actor_gender', models.CharField(max_length=30)),
                ('actor_birthday', models.DateField(default=None)),
                ('actor_place_of_birth', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=None)),
            ],
        ),
    ]
