# Generated by Django 4.1.5 on 2023-01-29 09:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, default='default_poster.jpg', upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=None)),
                ('overview', models.TextField(default=None)),
                ('director', models.CharField(default=None, max_length=50)),
                ('release', models.DateField(default=None)),
                ('runtime', models.CharField(default=None, max_length=20)),
                ('genre', models.TextField(default=None)),
                ('rating_avg', models.FloatField(default=None)),
                ('rating_num', models.IntegerField(default=None)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=100)),
                ('review_rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('review_text', models.TextField(blank=True, default=None)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('review_likes', models.IntegerField(default=0)),
                ('review_dislikes', models.IntegerField(default=0)),
                ('review_author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review_movie_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_movie', models.CharField(max_length=30)),
                ('actor_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='actors.actor')),
                ('movie_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
